### Fetch entities
GET http://localhost:8080/equipment
Content-type: application/json

### Fetch entity
GET http://localhost:8080/equipment/1
Content-type: application/json

### Fetch entity
GET http://localhost:8080/equipment/filter/tent
Content-type: application/json

### Create ticket
POST http://localhost:8080/equipment
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5OTA1MDk0LCJleHAiOjE1ODk5MDg2OTR9.aGNBYKQ-SBkOD_EmZXa25K4BScTT5Riw99nGBMwyZmY

{
  "name": "tent",
  "price": "20",
  "type": "tent",
  "rating": "1",
  "description": "Norm"
}

### Update entity
PUT http://localhost:8080/equipment/1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5OTA1MDk0LCJleHAiOjE1ODk5MDg2OTR9.aGNBYKQ-SBkOD_EmZXa25K4BScTT5Riw99nGBMwyZmY

{
  "name": "tent",
  "price": "18",
  "type": "tent",
  "rating": "1",
  "description": "Norm"
}

### Delete entity
DELETE http://localhost:8080/equipment/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5OTA1MDk0LCJleHAiOjE1ODk5MDg2OTR9.aGNBYKQ-SBkOD_EmZXa25K4BScTT5Riw99nGBMwyZmY

### Fetch entities
GET http://localhost:8080/booking
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5OTA1MDk0LCJleHAiOjE1ODk5MDg2OTR9.aGNBYKQ-SBkOD_EmZXa25K4BScTT5Riw99nGBMwyZmY

### Fetch entity
GET http://localhost:8080/booking/1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm5hQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX0NMSUVOVCIsImlhdCI6MTU4OTkwNTQ3MCwiZXhwIjoxNTg5OTA5MDcwfQ.0knCsP3eKG4d3N15PBNWebCi8xEPPuEADrO-ubjQDuo

### Fetch entity
GET http://localhost:8080/booking/user/1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm5hQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX0NMSUVOVCIsImlhdCI6MTU4OTkwNTQ3MCwiZXhwIjoxNTg5OTA5MDcwfQ.0knCsP3eKG4d3N15PBNWebCi8xEPPuEADrO-ubjQDuo

### Fetch entity
GET http://localhost:8080/booking/equipment/1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm5hQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX0NMSUVOVCIsImlhdCI6MTU4OTkwNTQ3MCwiZXhwIjoxNTg5OTA5MDcwfQ.0knCsP3eKG4d3N15PBNWebCi8xEPPuEADrO-ubjQDuo

### Create ticket
POST http://localhost:8080/booking
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm5hQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX0NMSUVOVCIsImlhdCI6MTU4OTk4MjA3NywiZXhwIjoxNTg5OTg1Njc3fQ.6qFqFfjJp4rXqoZDfh14hr7w56VIiU6r2qXvXxF3Qi8

{
  "touristId": "4",
  "equipmentId": "7",
  "date": "05/07/2020 20:00:00"
}

### Delete entity
DELETE http://localhost:8080/booking/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5OTA1MDk0LCJleHAiOjE1ODk5MDg2OTR9.aGNBYKQ-SBkOD_EmZXa25K4BScTT5Riw99nGBMwyZmY

### Fetch entities
GET http://localhost:8080/feedback
Content-type: application/json

### Fetch entity
GET http://localhost:8080/feedback/1
Content-type: application/json

### Fetch entity
GET http://localhost:8080/feedback/booking/1
Content-type: application/json

### Fetch entity
GET http://localhost:8080/feedback/equipment/1
Content-type: application/json

### Create ticket
POST http://localhost:8080/feedback
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm5hQGdtYWlsLmNvbSIsImF1dGgiOiJST0xFX0NMSUVOVCIsImlhdCI6MTU4OTk4MjA3NywiZXhwIjoxNTg5OTg1Njc3fQ.6qFqFfjJp4rXqoZDfh14hr7w56VIiU6r2qXvXxF3Qi8

{
  "bookingId": "24",
  "rating": "3",
  "text": "Norm",
  "date": "05/07/2020 20:00:00"
}

### Delete entity
DELETE http://localhost:8080/feedback/1

### Fetch entity
POST http://localhost:8080/user/login
Content-type: application/json

{
  "email": "admin@mail.com",
  "password": "admin"
}

### Fetch entity
POST http://localhost:8080/user/login
Content-type: application/json

{
  "email": "anna@gmail.com",
  "password": "P@ssw0rd"
}

### Create entity
POST http://localhost:8080/user/register
Content-type: application/json

{
  "name": "Anna",
  "email": "anna@gmail.com",
  "password": "P@ssw0rd"
}

### Create entity
POST http://localhost:8080/user/register
Content-type: application/json

{
  "name": "admin",
  "email": "admin@mail.com",
  "password": "admin"
}

### Fetch entity
GET http://localhost:8080/user
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5OTE5NjI5LCJleHAiOjE1ODk5MjMyMjl9.zFMm1-MBB0OIRIqQuNyRjuCgUzPx-e5zB5yC0EWHFmU
### Fetch entity
GET http://localhost:8085/user/isAdmin
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5OTA1MDk0LCJleHAiOjE1ODk5MDg2OTR9.aGNBYKQ-SBkOD_EmZXa25K4BScTT5Riw99nGBMwyZmY

### Fetch entity
GET http://localhost:8080/user/find/anna@gmail.com
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5OTE5NjI5LCJleHAiOjE1ODk5MjMyMjl9.zFMm1-MBB0OIRIqQuNyRjuCgUzPx-e5zB5yC0EWHFmU