### Fetch entities
GET http://localhost:8080/equipment
Content-type: application/json

### Fetch entity
GET http://localhost:8080/equipment/1
Content-type: application/json

### Fetch entity
GET http://localhost:8080/equipment/filter/tent
Content-type: application/json

### Create ticket
POST http://localhost:8080/equipment
Content-type: application/json

{
  "name": "tent",
  "price": "20",
  "type": "tent",
  "rating": "1",
  "description": "Norm"
}

### Update entity
PUT http://localhost:8080/equipment/1
Content-type: application/json

{
  "name": "tent",
  "price": "18",
  "type": "tent",
  "rating": "4",
  "description": "Norm"
}

### Delete entity
DELETE http://localhost:8080/equipment/1

### Fetch entities
GET http://localhost:8080/booking
Content-type: application/json

### Fetch entity
GET http://localhost:8080/booking/1
Content-type: application/json

### Fetch entity
GET http://localhost:8080/booking/user/1
Content-type: application/json

### Fetch entity
GET http://localhost:8080/booking/equipment/1
Content-type: application/json

### Create ticket
POST http://localhost:8080/booking
Content-type: application/json

{
  "touristId": "1",
  "equipmentId": "2",
  "date": "05/07/2020 20:00:00"
}

### Delete entity
DELETE http://localhost:8080/booking/1

### Fetch entities
GET http://localhost:8080/feedback
Content-type: application/json

### Fetch entity
GET http://localhost:8080/feedback/1
Content-type: application/json

### Fetch entity
GET http://localhost:8080/feedback/booking/1
Content-type: application/json

### Fetch entity
GET http://localhost:8080/feedback/equipment/1
Content-type: application/json

### Create ticket
POST http://localhost:8080/feedback
Content-type: application/json

{
  "bookingId": "1",
  "rating": "3",
  "text": "Norm",
  "date": "05/07/2020 20:00:00"
}

### Delete entity
DELETE http://localhost:8080/feedback/1

### Fetch entity
GET http://localhost:8080/user/signin
Content-type: application/json

{
  "email": "admin@mail.com",
  "password": "admin"
}

### Fetch entity
GET http://localhost:8080/user/signin
Content-type: application/json

{
  "email": "anna@gmail.com",
  "password": "P@ssw0rd"
}

### Create entity
POST http://localhost:8080/user/register
Content-type: application/json

{
  "name": "Anna",
  "email": "anna1@gmail.com",
  "password": "P@ssw0rd"
}

### Create entity
POST http://localhost:8080/user/register
Content-type: application/json

{
  "name": "admin",
  "email": "admin@mail.com",
  "password": "admin"
}

### Fetch entity
GET http://localhost:8080/user
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5ODI4NzE1LCJleHAiOjE1ODk4MzIzMTV9.yTw51BjNRUOB6JdSrtjsjnR14Wbn7ZRfZ-sNi7rFrHg

### Fetch entity
GET http://localhost:8080/user/1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5ODI4NzE1LCJleHAiOjE1ODk4MzIzMTV9.yTw51BjNRUOB6JdSrtjsjnR14Wbn7ZRfZ-sNi7rFrHg

### Fetch entity
GET http://localhost:8080/user/find/anna@gmail.com
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbkBtYWlsLmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNTg5ODI4NzE1LCJleHAiOjE1ODk4MzIzMTV9.yTw51BjNRUOB6JdSrtjsjnR14Wbn7ZRfZ-sNi7rFrHg